version: '3.7'

services:

  node:
    container_name: nodeapp
    image: nodeapp
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - nodeapp-network
    volumes:
      - ./logs:/var/www/logs
    depends_on:
      - mongodb
      - elasticsearch

  mongodb:
    container_name: mongodb
    image: mongo
    networks:
      - nodeapp-network
    ports:
      - "27017:27017"

  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.13
    environment:
      - discovery.type=single-node
    networks:
      - nodeapp-network
    ports:
      - "9200:9200"

networks:
  nodeapp-network:
    driver: bridge
